import { Inter } from 'next/font/google';
import './globals.scss';

import { ClientOnlyProps } from '#/types';
import AuthProvider from '@/components/authProvider/AuthProvider';
import Footer from '@/components/footer/Footer';
import Navbar from '@/components/navbar/Navbar';

import { ThemeProvider } from '@/context/ThemeContext';

import type { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next-Blog',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({ children }: ClientOnlyProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <div className="container">
              <Navbar />
              {children}
              <Footer />
            </div>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
